name: Deploy Tailwind to GitHub Pages

on:
  push:
    branches: [ main ]   # هر وقت روی main push شد اجرا میشه

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Tailwind
        run: npx tailwindcss -i ./src/input.css -o ./dist/output.css --minify

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
